//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AandN_Website.IntegrationServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogItem", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class CatalogItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        private int AvailableQtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AvailableQty {
            get {
                return this.AvailableQtyField;
            }
            set {
                if ((this.AvailableQtyField.Equals(value) != true)) {
                    this.AvailableQtyField = value;
                    this.RaisePropertyChanged("AvailableQty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryLevel", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class InventoryLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIDField;
        
        private int OnHandQtyField;
        
        private int ReservedQtyField;
        
        private int AvailableQtyField;
        
        private int ReorderPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIDField, value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OnHandQty {
            get {
                return this.OnHandQtyField;
            }
            set {
                if ((this.OnHandQtyField.Equals(value) != true)) {
                    this.OnHandQtyField = value;
                    this.RaisePropertyChanged("OnHandQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ReservedQty {
            get {
                return this.ReservedQtyField;
            }
            set {
                if ((this.ReservedQtyField.Equals(value) != true)) {
                    this.ReservedQtyField = value;
                    this.RaisePropertyChanged("ReservedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AvailableQty {
            get {
                return this.AvailableQtyField;
            }
            set {
                if ((this.AvailableQtyField.Equals(value) != true)) {
                    this.AvailableQtyField = value;
                    this.RaisePropertyChanged("AvailableQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ReorderPoint {
            get {
                return this.ReorderPointField;
            }
            set {
                if ((this.ReorderPointField.Equals(value) != true)) {
                    this.ReorderPointField = value;
                    this.RaisePropertyChanged("ReorderPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingAddressField;
        
        private decimal CartTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AandN_Website.IntegrationServiceRef.OrderItemDto[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BillingAddress {
            get {
                return this.BillingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressField, value) != true)) {
                    this.BillingAddressField = value;
                    this.RaisePropertyChanged("BillingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ShippingAddress {
            get {
                return this.ShippingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingAddressField, value) != true)) {
                    this.ShippingAddressField = value;
                    this.RaisePropertyChanged("ShippingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CartTotal {
            get {
                return this.CartTotalField;
            }
            set {
                if ((this.CartTotalField.Equals(value) != true)) {
                    this.CartTotalField = value;
                    this.RaisePropertyChanged("CartTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PromotionCode {
            get {
                return this.PromotionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionCodeField, value) != true)) {
                    this.PromotionCodeField = value;
                    this.RaisePropertyChanged("PromotionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AandN_Website.IntegrationServiceRef.OrderItemDto[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItemDto", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class OrderItemDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        private int QuantityField;
        
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderConfirmation", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class OrderConfirmation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        private System.DateTime OrderDateField;
        
        private AandN_Website.IntegrationServiceRef.TimeSpan OrderTimeField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public AandN_Website.IntegrationServiceRef.TimeSpan OrderTime {
            get {
                return this.OrderTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTimeField, value) != true)) {
                    this.OrderTimeField = value;
                    this.RaisePropertyChanged("OrderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentStatus", Namespace="http://aandn.com/integration")]
    [System.SerializableAttribute()]
    public partial class ShipmentStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingNumberField;
        
        private System.DateTime ShippedDateField;
        
        private System.DateTime EstimatedDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShipmentID {
            get {
                return this.ShipmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentIDField, value) != true)) {
                    this.ShipmentIDField = value;
                    this.RaisePropertyChanged("ShipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CarrierInfo {
            get {
                return this.CarrierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierInfoField, value) != true)) {
                    this.CarrierInfoField = value;
                    this.RaisePropertyChanged("CarrierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TrackingNumber {
            get {
                return this.TrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingNumberField, value) != true)) {
                    this.TrackingNumberField = value;
                    this.RaisePropertyChanged("TrackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime ShippedDate {
            get {
                return this.ShippedDateField;
            }
            set {
                if ((this.ShippedDateField.Equals(value) != true)) {
                    this.ShippedDateField = value;
                    this.RaisePropertyChanged("ShippedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EstimatedDelivery {
            get {
                return this.EstimatedDeliveryField;
            }
            set {
                if ((this.EstimatedDeliveryField.Equals(value) != true)) {
                    this.EstimatedDeliveryField = value;
                    this.RaisePropertyChanged("EstimatedDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aandn.com/integration", ConfigurationName="IntegrationServiceRef.IntegrationServiceSoap")]
    public interface IntegrationServiceSoap {
        
        // CODEGEN: Generating message contract since element name category from namespace http://aandn.com/integration is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetCatalogItems", ReplyAction="*")]
        AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse GetCatalogItems(AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetCatalogItems", ReplyAction="*")]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse> GetCatalogItemsAsync(AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest request);
        
        // CODEGEN: Generating message contract since element name productID from namespace http://aandn.com/integration is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetInventoryLevels", ReplyAction="*")]
        AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse GetInventoryLevels(AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetInventoryLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse> GetInventoryLevelsAsync(AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest request);
        
        // CODEGEN: Generating message contract since element name order from namespace http://aandn.com/integration is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/SubmitOrder", ReplyAction="*")]
        AandN_Website.IntegrationServiceRef.SubmitOrderResponse SubmitOrder(AandN_Website.IntegrationServiceRef.SubmitOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/SubmitOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.SubmitOrderResponse> SubmitOrderAsync(AandN_Website.IntegrationServiceRef.SubmitOrderRequest request);
        
        // CODEGEN: Generating message contract since element name trackingNumber from namespace http://aandn.com/integration is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetShipmentStatus", ReplyAction="*")]
        AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse GetShipmentStatus(AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aandn.com/integration/GetShipmentStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse> GetShipmentStatusAsync(AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogItems", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetCatalogItemsRequestBody Body;
        
        public GetCatalogItemsRequest() {
        }
        
        public GetCatalogItemsRequest(AandN_Website.IntegrationServiceRef.GetCatalogItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetCatalogItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetCatalogItemsRequestBody() {
        }
        
        public GetCatalogItemsRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCatalogItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCatalogItemsResponse", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetCatalogItemsResponseBody Body;
        
        public GetCatalogItemsResponse() {
        }
        
        public GetCatalogItemsResponse(AandN_Website.IntegrationServiceRef.GetCatalogItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetCatalogItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AandN_Website.IntegrationServiceRef.CatalogItem[] GetCatalogItemsResult;
        
        public GetCatalogItemsResponseBody() {
        }
        
        public GetCatalogItemsResponseBody(AandN_Website.IntegrationServiceRef.CatalogItem[] GetCatalogItemsResult) {
            this.GetCatalogItemsResult = GetCatalogItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryLevelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryLevels", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequestBody Body;
        
        public GetInventoryLevelsRequest() {
        }
        
        public GetInventoryLevelsRequest(AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetInventoryLevelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productID;
        
        public GetInventoryLevelsRequestBody() {
        }
        
        public GetInventoryLevelsRequestBody(string productID) {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryLevelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryLevelsResponse", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponseBody Body;
        
        public GetInventoryLevelsResponse() {
        }
        
        public GetInventoryLevelsResponse(AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetInventoryLevelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AandN_Website.IntegrationServiceRef.InventoryLevel[] GetInventoryLevelsResult;
        
        public GetInventoryLevelsResponseBody() {
        }
        
        public GetInventoryLevelsResponseBody(AandN_Website.IntegrationServiceRef.InventoryLevel[] GetInventoryLevelsResult) {
            this.GetInventoryLevelsResult = GetInventoryLevelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitOrder", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.SubmitOrderRequestBody Body;
        
        public SubmitOrderRequest() {
        }
        
        public SubmitOrderRequest(AandN_Website.IntegrationServiceRef.SubmitOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class SubmitOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AandN_Website.IntegrationServiceRef.OrderDto order;
        
        public SubmitOrderRequestBody() {
        }
        
        public SubmitOrderRequestBody(AandN_Website.IntegrationServiceRef.OrderDto order) {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitOrderResponse", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.SubmitOrderResponseBody Body;
        
        public SubmitOrderResponse() {
        }
        
        public SubmitOrderResponse(AandN_Website.IntegrationServiceRef.SubmitOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class SubmitOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AandN_Website.IntegrationServiceRef.OrderConfirmation SubmitOrderResult;
        
        public SubmitOrderResponseBody() {
        }
        
        public SubmitOrderResponseBody(AandN_Website.IntegrationServiceRef.OrderConfirmation SubmitOrderResult) {
            this.SubmitOrderResult = SubmitOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipmentStatus", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetShipmentStatusRequestBody Body;
        
        public GetShipmentStatusRequest() {
        }
        
        public GetShipmentStatusRequest(AandN_Website.IntegrationServiceRef.GetShipmentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetShipmentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string trackingNumber;
        
        public GetShipmentStatusRequestBody() {
        }
        
        public GetShipmentStatusRequestBody(string trackingNumber) {
            this.trackingNumber = trackingNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipmentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipmentStatusResponse", Namespace="http://aandn.com/integration", Order=0)]
        public AandN_Website.IntegrationServiceRef.GetShipmentStatusResponseBody Body;
        
        public GetShipmentStatusResponse() {
        }
        
        public GetShipmentStatusResponse(AandN_Website.IntegrationServiceRef.GetShipmentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://aandn.com/integration")]
    public partial class GetShipmentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AandN_Website.IntegrationServiceRef.ShipmentStatus GetShipmentStatusResult;
        
        public GetShipmentStatusResponseBody() {
        }
        
        public GetShipmentStatusResponseBody(AandN_Website.IntegrationServiceRef.ShipmentStatus GetShipmentStatusResult) {
            this.GetShipmentStatusResult = GetShipmentStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationServiceSoapChannel : AandN_Website.IntegrationServiceRef.IntegrationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationServiceSoapClient : System.ServiceModel.ClientBase<AandN_Website.IntegrationServiceRef.IntegrationServiceSoap>, AandN_Website.IntegrationServiceRef.IntegrationServiceSoap {
        
        public IntegrationServiceSoapClient() {
        }
        
        public IntegrationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetCatalogItems(AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest request) {
            return base.Channel.GetCatalogItems(request);
        }
        
        public AandN_Website.IntegrationServiceRef.CatalogItem[] GetCatalogItems(string category) {
            AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest inValue = new AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetCatalogItemsRequestBody();
            inValue.Body.category = category;
            AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse retVal = ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetCatalogItems(inValue);
            return retVal.Body.GetCatalogItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse> AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetCatalogItemsAsync(AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest request) {
            return base.Channel.GetCatalogItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetCatalogItemsResponse> GetCatalogItemsAsync(string category) {
            AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest inValue = new AandN_Website.IntegrationServiceRef.GetCatalogItemsRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetCatalogItemsRequestBody();
            inValue.Body.category = category;
            return ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetCatalogItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetInventoryLevels(AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest request) {
            return base.Channel.GetInventoryLevels(request);
        }
        
        public AandN_Website.IntegrationServiceRef.InventoryLevel[] GetInventoryLevels(string productID) {
            AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest inValue = new AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequestBody();
            inValue.Body.productID = productID;
            AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse retVal = ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetInventoryLevels(inValue);
            return retVal.Body.GetInventoryLevelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse> AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetInventoryLevelsAsync(AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest request) {
            return base.Channel.GetInventoryLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetInventoryLevelsResponse> GetInventoryLevelsAsync(string productID) {
            AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest inValue = new AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetInventoryLevelsRequestBody();
            inValue.Body.productID = productID;
            return ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetInventoryLevelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AandN_Website.IntegrationServiceRef.SubmitOrderResponse AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.SubmitOrder(AandN_Website.IntegrationServiceRef.SubmitOrderRequest request) {
            return base.Channel.SubmitOrder(request);
        }
        
        public AandN_Website.IntegrationServiceRef.OrderConfirmation SubmitOrder(AandN_Website.IntegrationServiceRef.OrderDto order) {
            AandN_Website.IntegrationServiceRef.SubmitOrderRequest inValue = new AandN_Website.IntegrationServiceRef.SubmitOrderRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.SubmitOrderRequestBody();
            inValue.Body.order = order;
            AandN_Website.IntegrationServiceRef.SubmitOrderResponse retVal = ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).SubmitOrder(inValue);
            return retVal.Body.SubmitOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.SubmitOrderResponse> AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.SubmitOrderAsync(AandN_Website.IntegrationServiceRef.SubmitOrderRequest request) {
            return base.Channel.SubmitOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.SubmitOrderResponse> SubmitOrderAsync(AandN_Website.IntegrationServiceRef.OrderDto order) {
            AandN_Website.IntegrationServiceRef.SubmitOrderRequest inValue = new AandN_Website.IntegrationServiceRef.SubmitOrderRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.SubmitOrderRequestBody();
            inValue.Body.order = order;
            return ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).SubmitOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetShipmentStatus(AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest request) {
            return base.Channel.GetShipmentStatus(request);
        }
        
        public AandN_Website.IntegrationServiceRef.ShipmentStatus GetShipmentStatus(string trackingNumber) {
            AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest inValue = new AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetShipmentStatusRequestBody();
            inValue.Body.trackingNumber = trackingNumber;
            AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse retVal = ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetShipmentStatus(inValue);
            return retVal.Body.GetShipmentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse> AandN_Website.IntegrationServiceRef.IntegrationServiceSoap.GetShipmentStatusAsync(AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest request) {
            return base.Channel.GetShipmentStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<AandN_Website.IntegrationServiceRef.GetShipmentStatusResponse> GetShipmentStatusAsync(string trackingNumber) {
            AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest inValue = new AandN_Website.IntegrationServiceRef.GetShipmentStatusRequest();
            inValue.Body = new AandN_Website.IntegrationServiceRef.GetShipmentStatusRequestBody();
            inValue.Body.trackingNumber = trackingNumber;
            return ((AandN_Website.IntegrationServiceRef.IntegrationServiceSoap)(this)).GetShipmentStatusAsync(inValue);
        }
    }
}
